site_name: maverick-note
theme: readthedocs
nav:
- Home: 'index.md'
- Django:
    - 'RESTful的不同View类': 'RESTView.md'
    - '三种Filter': 'filter.md'
    - 'CROS': 'CROS.md'
    - 'JWT用户认证': 'JWT用户认证.md'
    - 'DRF的传统认证': 'DRF-Authentication.md'
    

